---

palava_web_install_dir: /var/www/palava-web
palava_web_log_dir: /var/log/palava-web
palava_web_repo: https://github.com/palavatv/palava-web.git
palava_web_version: v1.1.0
palava_web_environment: production
palava_web_rtc_url: wss://machine.palava.tv
